### ISSUE TITLE
Cannot install Bootstrap4 module from Jahia Studio

### ISSUE THREAD

**Issue by pakjiddat** [Jahia/bootstrap4#19]
I tried to install Bootstrap4 module from Jahia Studio but it gave the following error: 

`Package https://store.jahia.com/files/live/sites/private-app-store/contents/modules-repository/packages/Bootstrap4/Bootstrap4-4.6.2/bootstrap4_package_4.6.2.jar need the license org.jahia.core to be installed.`

**Comment by pvollenweider** [comment]
Hello,
What exact version of Jahia do you use and which module did you try to install? bootstrap4-core? bootstrap4-components? 
Philippe

**Comment by pvollenweider** [comment]
If you want to get the bootstrap4-components sources for release 4.6.2, then you should follow the following procedure:
## Get module from sources
Click on the "get module from sources"
![Get module 1](https://github.com/Jahia/bootstrap4/blob/master/misc/get-module-from-sources1.png?raw=true)

## Enter the following settings
- SCM type: Git
- URI: https://github.com/Jahia/bootstrap4.git
- Module ID (artifactId): bootstrap4-components
- Branch or tag: bootstrap4-modules-4.6.2
![Get module 2](https://github.com/Jahia/bootstrap4/blob/master/misc/get-module-from-sources2.png?raw=true)

It should work like this. Be sure to enter a **https** url instead of a **git** URL.
As it's a multiple module project, be sure to enter a module ID (bootstrap4-components or bootstrap4-core).
For the tag, set an existing tag. Get the full list at https://github.com/Jahia/bootstrap4/tags

Cheers,

Philippe
